'''
@author Vinayak
@email vnayak@okkular.io / nayakvinayak95@gmail.com
@create date 2022-02-17 09:24:09
@modify date 2022-02-17 18:28:09
@desc [Generate 3rd Degree polynomial based on mobile number]
'''
from typing import List

def generate_polynomial() -> List:
    """Prompts the user for input and generates a polynomial based on the mobile number generated by the user. Assumption: Mobile numbers can only be 10 digits long 

    Returns:
        List: Co-efficient list for the polynomial
    """
    number = input("Enter your cell number:\n")

    # Validate the entered input
    try:
        _ = int(number.strip())
    except Exception as e:
        raise AssertionError("Incorrect input format. Please enter a valid number")

    if len(number.strip()) != 10:
        raise AssertionError("Mobile number must be 10 digits long!")  
    
    polynomial_coefs = []
    for idx, chr in enumerate(number):
        coef = int(chr)
        # In case there's a zero in the mobile number replace it with a 3
        if coef == 0: coef = 3
        # Alternate between positive and negative co-efficients
        if idx % 2 == 1:
            coef = -1 * coef
        polynomial_coefs.append(coef)
    
    return polynomial_coefs

def display_polynomial(coefs: List):
    """[Given a list of co-efficients, displays a polynomial]

    Args:
        coefs (List): A coe-efficient polynomial
    """
    terms = ["x^3", "x^2y", "xy^2", "y^3", "x^2", "xy", "y^2", "x", "y", "1"]
    
    polynomial = ""
    for idx, (coef, term) in enumerate(zip(coefs, terms)):
        if idx % 2 == 0:
            polynomial += f"+{coef}{term}"
        else:
            polynomial += f"{coef}{term}"
    polynomial = polynomial[:-1]
    print(polynomial)
        

# poly = generate_polynomial()
# display_polynomial(poly)
        
